from utilities.pre_processing_base import pre_processing_base
from utilities.pre_processing_ft import pre_processing_ft
from utilities.pre_processing_none import pre_processing_none
from utilities.pre_processing_t import pre_processing_t
from utilities.pre_processing_f import pre_processing_f